# Generated by Django 5.1.4 on 2024-12-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
