# Generated by Django 5.1.4 on 2024-12-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0003_invoice_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
