# Generated by Django 5.1.4 on 2024-12-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0004_invoice_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
    ]
